\c capstonelegaldevdb;

CREATE VIEW capstonelegalschema.JUDGE_VIEW AS 
SELECT 
    J.JUDGE_ID, 
    J.JUDGE_FIRST_NAME, 
    J.JUDGE_LAST_NAME, 
    JT.JUDGE_TYPE_NAME, 
    J.JUDGE_EMAIL, 
    CT.COURT_TYPE_NAME, 
    J.JUDGE_STREET_1, 
    J.JUDGE_STREET_2, 
    CI.CITY_NAME AS JUDGE_CITY_NAME, 
    DI.DISTRICT_NAME AS JUDGE_DISTRICT_NAME, 
    ST.STATE_NAME AS JUDGE_STATE_NAME, 
    CO.COUNTRY_NAME AS JUDGE_COUNTRY_NAME
FROM 
    capstonelegalschema.JUDGE J 
INNER JOIN 
    capstonelegalschema.JUDGE_TYPE JT ON J.JUDGE_TYPE_ID = JT.JUDGE_TYPE_ID
INNER JOIN 
    capstonelegalschema.COURT C ON J.JUDGE_COURT_ID = C.COURT_ID
INNER JOIN 
    capstonelegalschema.COURT_TYPE CT ON C.COURT_TYPE_ID = CT.COURT_TYPE_ID
INNER JOIN 
    capstonelegalschema.CITY CI ON J.JUDGE_CITY_ID = CI.CITY_ID
INNER JOIN 
    capstonelegalschema.DISTRICT DI ON J.JUDGE_DISTRICT_ID = DI.DISTRICT_ID
INNER JOIN 
    capstonelegalschema.STATE ST ON J.JUDGE_STATE_ID = ST.STATE_ID
INNER JOIN 
    capstonelegalschema.COUNTRY CO ON J.JUDGE_COUNTRY_ID = CO.COUNTRY_ID;
