CREATE DATABASE capstonelegaldevdb;

\c capstonelegaldevdb;

CREATE SCHEMA capstonelegalschema;

CREATE TABLE capstonelegalschema.COUNTRY (
COUNTRY_ID VARCHAR(50) PRIMARY KEY, 
COUNTRY_NAME VARCHAR(100) NOT NULL, 
COUNTRY_INITIALS VARCHAR(10) NOT NULL
);

CREATE TABLE capstonelegalschema.STATE (
STATE_ID VARCHAR(50) PRIMARY KEY, 
STATE_NAME VARCHAR(100) NOT NULL, 
STATE_INITIALS VARCHAR(10) NOT NULL,
COUNTRY_ID VARCHAR(50) NOT NULL,
CONSTRAINT FK_COUNTRY_ID FOREIGN KEY (COUNTRY_ID) REFERENCES capstonelegalschema.COUNTRY(COUNTRY_ID)
);

CREATE TABLE capstonelegalschema.DISTRICT (
DISTRICT_ID VARCHAR(50) PRIMARY KEY, 
DISTRICT_NAME VARCHAR(100) NOT NULL, 
STATE_ID VARCHAR(50) NOT NULL,
CONSTRAINT FK_STATE_ID FOREIGN KEY (STATE_ID) REFERENCES capstonelegalschema.STATE(STATE_ID)
);

CREATE TABLE capstonelegalschema.CITY (
CITY_ID VARCHAR(50) PRIMARY KEY, 
CITY_NAME VARCHAR(100) NOT NULL, 
DISTRICT_ID VARCHAR(50) NOT NULL,
CONSTRAINT FK_DISTRICT_ID FOREIGN KEY (DISTRICT_ID) REFERENCES capstonelegalschema.DISTRICT(DISTRICT_ID)
);

CREATE TABLE capstonelegalschema.CONTACT_TYPE (
CONTACT_TYPE_ID VARCHAR(50) PRIMARY KEY, 
CONTACT_TYPE_NAME VARCHAR(100) NOT NULL, 
CONTACT_TYPE_DESCRIPTION VARCHAR(300) NOT NULL
);

CREATE TABLE capstonelegalschema.CREDENTIALS (
CREDENTIALS_ID VARCHAR(50) PRIMARY KEY,
LOGIN_ID VARCHAR(100) NOT NULL,
LOGIN_PASSWORD VARCHAR(100) NOT NULL,
CREDENTIALS_CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
LAST_SUCCESSFUL_LOGIN TIMESTAMP,
LAST_FAILED_LOGIN TIMESTAMP,
LAST_UPDATED TIMESTAMP
);

CREATE TABLE capstonelegalschema.ROLE (
ROLE_ID VARCHAR(50) PRIMARY KEY, 
ROLE_NAME VARCHAR(100) NOT NULL, 
ROLE_DESCRIPTION VARCHAR(300) NOT NULL
);

CREATE TABLE capstonelegalschema.ORGANIZATION (
ORGANIZATION_ID VARCHAR(50) PRIMARY KEY, 
ORGANIZATION_NAME VARCHAR(100) NOT NULL, 
ORGANIZATION_DESCRIPTION VARCHAR(300) NOT NULL,
ORGANIZATION_EMAIL VARCHAR(100) NOT NULL, 
ORGANIZATION_PHONE VARCHAR(50) NOT NULL, 
ORGANIZATION_COUNTRY_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.COUNTRY(COUNTRY_ID), 
ORGANIZATION_STATE_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.STATE(STATE_ID),
ORGANIZATION_DISTRICT_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.DISTRICT(DISTRICT_ID),
ORGANIZATION_CITY_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.CITY(CITY_ID),
ORGANIZATION_STREET_1 VARCHAR(300) NOT NULL,
ORGANIZATION_STREET_2 VARCHAR(300),
ORGANIZATION_STREET_ZIPCODE VARCHAR(50)
);

CREATE TABLE capstonelegalschema.DEPARTMENT (
DEPARTMENT_ID VARCHAR(50) PRIMARY KEY, 
DEPARTMENT_NAME VARCHAR(100) NOT NULL, 
DEPARTMENT_DESCRIPTION VARCHAR(300) NOT NULL,
DEPARTMENT_ORGANIZATION_ID VARCHAR(50) NOT NULL,
CONSTRAINT FK_DEPARTMENT_ORGANIZATION_ID FOREIGN KEY (DEPARTMENT_ORGANIZATION_ID) REFERENCES capstonelegalschema.ORGANIZATION(ORGANIZATION_ID)
);

CREATE TABLE capstonelegalschema.EMPLOYEE (
EMPLOYEE_ID VARCHAR(50) PRIMARY KEY, 
EMPLOYEE_FIRST_NAME VARCHAR(100) NOT NULL, 
EMPLOYEE_LAST_NAME VARCHAR(100) NOT NULL, 
EMPLOYEE_ORGANIZATION_ID VARCHAR(50) NOT NULL,
EMPLOYEE_DEPARTMENT_ID VARCHAR(50) NOT NULL,
EMPLOYEE_ROLE_ID VARCHAR(50) NOT NULL,
EMPLOYEE_DATE_OF_JOIN VARCHAR(50) NOT NULL,
EMPLOYEE_STATUS VARCHAR(100) NOT NULL,
EMPLOYEE_EMAIL VARCHAR(100) NOT NULL, 
EMPLOYEE_PHONE VARCHAR(50) NOT NULL, 
EMPLOYEE_COUNTRY_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.COUNTRY(COUNTRY_ID), 
EMPLOYEE_STATE_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.STATE(STATE_ID),
EMPLOYEE_DISTRICT_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.DISTRICT(DISTRICT_ID),
EMPLOYEE_CITY_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.CITY(CITY_ID),
EMPLOYEE_STREET_1 VARCHAR(300) NOT NULL,
EMPLOYEE_STREET_2 VARCHAR(300),
EMPLOYEE_STREET_ZIPCODE VARCHAR(50),
EMPLOYEE_DESCRIPTION VARCHAR(300),
EMPLOYEE_CREDENTIALS_ID VARCHAR(50),
CONSTRAINT FK_EMPLOYEE_CREDENTIALS_ID FOREIGN KEY (EMPLOYEE_CREDENTIALS_ID) REFERENCES capstonelegalschema.CREDENTIALS(CREDENTIALS_ID),
CONSTRAINT FK_EMPLOYEE_ORGANIZATION_ID FOREIGN KEY (EMPLOYEE_ORGANIZATION_ID) REFERENCES capstonelegalschema.ORGANIZATION(ORGANIZATION_ID),
CONSTRAINT FK_EMPLOYEE_DEPARTMENT_ID FOREIGN KEY (EMPLOYEE_DEPARTMENT_ID) REFERENCES capstonelegalschema.DEPARTMENT(DEPARTMENT_ID),
CONSTRAINT FK_EMPLOYEE_ROLE_ID FOREIGN KEY (EMPLOYEE_ROLE_ID) REFERENCES capstonelegalschema.ROLE(ROLE_ID)
);

CREATE TABLE capstonelegalschema.CONTACT (
CONTACT_ID VARCHAR(50) PRIMARY KEY, 
CONTACT_FIRST_NAME VARCHAR(100) NOT NULL, 
CONTACT_LAST_NAME VARCHAR(100) NOT NULL, 
CONTACT_TYPE_ID VARCHAR(50) NOT NULL, 
CONTACT_EMAIL VARCHAR(100) NOT NULL, 
CONTACT_PHONE VARCHAR(50) NOT NULL, 
CONTACT_COUNTRY_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.COUNTRY(COUNTRY_ID), 
CONTACT_STATE_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.STATE(STATE_ID),
CONTACT_DISTRICT_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.DISTRICT(DISTRICT_ID),
CONTACT_CITY_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.CITY(CITY_ID),
CONTACT_STREET_1 VARCHAR(300) NOT NULL,
CONTACT_STREET_2 VARCHAR(300),
CONTACT_STREET_ZIPCODE VARCHAR(50),
CONTACT_DESCRIPTION VARCHAR(300),
CONTACT_CREDENTIALS_ID VARCHAR(50),
CONSTRAINT FK_CONTACT_CREDENTIALS_ID FOREIGN KEY (CONTACT_CREDENTIALS_ID) REFERENCES capstonelegalschema.CREDENTIALS(CREDENTIALS_ID),
CONSTRAINT FK_CONTACT_TYPE_ID FOREIGN KEY (CONTACT_TYPE_ID) REFERENCES capstonelegalschema.CONTACT_TYPE(CONTACT_TYPE_ID)
);
CREATE TABLE capstonelegalschema.LEGAL_PRACTICE_TYPE (
LEGAL_PRACTICE_TYPE_ID VARCHAR(50) PRIMARY KEY, 
LEGAL_PRACTICE_TYPE_NAME VARCHAR(100) NOT NULL, 
LEGAL_PRACTICE_TYPE_DESCRIPTION VARCHAR(300) NOT NULL
);

CREATE TABLE capstonelegalschema.LEGAL_PRACTICE_SUB_CATEGORY (
LEGAL_PRACTICE_SUB_CATEGORY_ID VARCHAR(50) PRIMARY KEY, 
LEGAL_PRACTICE_TYPE_ID VARCHAR(50) NOT NULL, 
LEGAL_PRACTICE_SUB_CATEGORY_NAME VARCHAR(100) NOT NULL, 
LEGAL_PRACTICE_SUB_CATEGORY_DESCRIPTION VARCHAR(300) NOT NULL,
CONSTRAINT FK_LEGAL_PRACTICE_TYPE_ID FOREIGN KEY (LEGAL_PRACTICE_TYPE_ID) REFERENCES capstonelegalschema.LEGAL_PRACTICE_TYPE(LEGAL_PRACTICE_TYPE_ID)
);

CREATE TABLE capstonelegalschema.EMPLOYEE_SPECIALITY_ASSOCIATION (
EMPLOYEE_SPECIALITY_ASSOCIATION_ID VARCHAR(50) PRIMARY KEY, 
EMPLOYEE_SPECIALITY_EMPLOYEE_ID VARCHAR(50) NOT NULL, 
EMPLOYEE_SPECIALITY_LEGAL_PRACTICE_SUB_CATEGORY_ID VARCHAR(50) NOT NULL, 
EMPLOYEE_SPECIALITY_LEGAL_PRACTICE_TYPE_ID VARCHAR(50) NOT NULL,
CONSTRAINT FK_EMPLOYEE_SPECIALITY_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_SPECIALITY_EMPLOYEE_ID) REFERENCES capstonelegalschema.EMPLOYEE(EMPLOYEE_ID),
CONSTRAINT FK_EMPLOYEE_SPECIALITY_LEGAL_PRACTICE_SUB_CATEGORY_ID FOREIGN KEY (EMPLOYEE_SPECIALITY_LEGAL_PRACTICE_SUB_CATEGORY_ID) REFERENCES capstonelegalschema.LEGAL_PRACTICE_SUB_CATEGORY(LEGAL_PRACTICE_SUB_CATEGORY_ID),
CONSTRAINT FK_EMPLOYEE_SPECIALITY_LEGAL_PRACTICE_TYPE_ID FOREIGN KEY (EMPLOYEE_SPECIALITY_LEGAL_PRACTICE_TYPE_ID) REFERENCES capstonelegalschema.LEGAL_PRACTICE_TYPE(LEGAL_PRACTICE_TYPE_ID)
);

CREATE TABLE capstonelegalschema.COURT_TYPE (
COURT_TYPE_ID VARCHAR(50) PRIMARY KEY, 
COURT_TYPE_NAME VARCHAR(100) NOT NULL, 
COURT_TYPE_DESCRIPTION VARCHAR(300) NOT NULL
);

CREATE TABLE capstonelegalschema.COURT (
COURT_ID VARCHAR(50) PRIMARY KEY, 
COURT_TYPE_ID VARCHAR(50) NOT NULL, 
COURT_TYPE_NAME VARCHAR(100) NOT NULL, 
COURT_COUNTRY_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.COUNTRY(COUNTRY_ID), 
COURT_STATE_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.STATE(STATE_ID),
COURT_DISTRICT_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.DISTRICT(DISTRICT_ID),
COURT_CITY_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.CITY(CITY_ID),
COURT_STREET_1 VARCHAR(300) NOT NULL,
COURT_STREET_2 VARCHAR(300),
COURT_STREET_ZIPCODE VARCHAR(50),
CONSTRAINT FK_COURT_TYPE_ID FOREIGN KEY (COURT_TYPE_ID) REFERENCES capstonelegalschema.COURT_TYPE(COURT_TYPE_ID)
);

CREATE TABLE capstonelegalschema.JUDGE_TYPE (
JUDGE_TYPE_ID VARCHAR(50) PRIMARY KEY, 
JUDGE_TYPE_NAME VARCHAR(100) NOT NULL, 
JUDGE_TYPE_DESCRIPTION VARCHAR(300) NOT NULL
);

CREATE TABLE capstonelegalschema.JUDGE (
JUDGE_ID VARCHAR(50) PRIMARY KEY, 
JUDGE_TYPE_ID VARCHAR(50) NOT NULL,
JUDGE_COURT_ID VARCHAR(50) NOT NULL,
JUDGE_FIRST_NAME VARCHAR(100) NOT NULL, 
JUDGE_LAST_NAME VARCHAR(100) NOT NULL, 
JUDGE_EMAIL VARCHAR(100) NOT NULL, 
JUDGE_COUNTRY_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.COUNTRY(COUNTRY_ID), 
JUDGE_STATE_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.STATE(STATE_ID),
JUDGE_DISTRICT_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.DISTRICT(DISTRICT_ID),
JUDGE_CITY_ID VARCHAR(50) NOT NULL REFERENCES capstonelegalschema.CITY(CITY_ID),
JUDGE_STREET_1 VARCHAR(300) NOT NULL,
JUDGE_STREET_2 VARCHAR(300),
JUDGE_STREET_ZIPCODE VARCHAR(50),
JUDGE_CREDENTIALS_ID VARCHAR(50),
CONSTRAINT FK_JUDGE_CREDENTIALS_ID FOREIGN KEY (JUDGE_CREDENTIALS_ID) REFERENCES capstonelegalschema.CREDENTIALS(CREDENTIALS_ID),
CONSTRAINT FK_JUDGE_TYPE_ID FOREIGN KEY (JUDGE_TYPE_ID) REFERENCES capstonelegalschema.JUDGE_TYPE(JUDGE_TYPE_ID),
CONSTRAINT FK_JUDGE_COURT_ID FOREIGN KEY (JUDGE_COURT_ID) REFERENCES capstonelegalschema.COURT(COURT_ID)
);

CREATE TABLE capstonelegalschema.JUDGE_SPECIALITY_ASSOCIATION (
JUDGE_SPECIALITY_ASSOCIATION_ID VARCHAR(50) PRIMARY KEY, 
JUDGE_SPECIALITY_JUDGE_ID VARCHAR(50) NOT NULL, 
JUDGE_SPECIALITY_LEGAL_PRACTICE_SUB_CATEGORY_ID VARCHAR(50) NOT NULL, 
JUDGE_SPECIALITY_LEGAL_PRACTICE_TYPE_ID VARCHAR(50) NOT NULL,
CONSTRAINT FK_JUDGE_SPECIALITY_JUDGE_ID FOREIGN KEY (JUDGE_SPECIALITY_JUDGE_ID) REFERENCES capstonelegalschema.JUDGE(JUDGE_ID),
CONSTRAINT FK_JUDGE_SPECIALITY_LEGAL_PRACTICE_SUB_CATEGORY_ID FOREIGN KEY (JUDGE_SPECIALITY_LEGAL_PRACTICE_SUB_CATEGORY_ID) REFERENCES capstonelegalschema.LEGAL_PRACTICE_SUB_CATEGORY(LEGAL_PRACTICE_SUB_CATEGORY_ID),
CONSTRAINT FK_JUDGE_SPECIALITY_LEGAL_PRACTICE_TYPE_ID FOREIGN KEY (JUDGE_SPECIALITY_LEGAL_PRACTICE_TYPE_ID) REFERENCES capstonelegalschema.LEGAL_PRACTICE_TYPE(LEGAL_PRACTICE_TYPE_ID)
);

CREATE TABLE capstonelegalschema.LEGAL_CASE (
LEGAL_CASE_ID VARCHAR(50) PRIMARY KEY,
LEGAL_CASE_TITLE VARCHAR(100) NOT NULL,
LEGAL_CASE_DESCRIPTION VARCHAR(1000) NOT NULL,
LEGAL_CASE_STATUS VARCHAR(50) NOT NULL,
LEGAL_CASE_ORGANIZATION_ID VARCHAR(50),
LEGAL_CASE_DOCUMENT BYTEA,
LEGAL_CASE_DATE DATE,
CONSTRAINT FK_LEGAL_CASE_ORGANIZATION_ID FOREIGN KEY (LEGAL_CASE_ORGANIZATION_ID) REFERENCES capstonelegalschema.ORGANIZATION(ORGANIZATION_ID)
);

CREATE TABLE capstonelegalschema.LEGAL_DOCUMENT_TYPE ( 
LEGAL_DOCUMENT_TYPE_ID VARCHAR(50) PRIMARY KEY, 
LEGAL_DOCUMENT_TYPE_NAME VARCHAR(100) NOT NULL, 
LEGAL_DOCUMENT_TYPE_DESCRIPTION VARCHAR(300) NOT NULL
);

CREATE TABLE capstonelegalschema.LEGAL_DOCUMENT (
LEGAL_DOCUMENT_ID VARCHAR(50) PRIMARY KEY,
LEGAL_DOCUMENT_TYPE_ID VARCHAR(50) NOT NULL,
LEGAL_DOCUMENT_TITLE VARCHAR(100) NOT NULL,
LEGAL_DOCUMENT_DESCRIPTION VARCHAR(1000) NOT NULL,
LEGAL_DOCUMENT_STATUS VARCHAR(50) NOT NULL,
LEGAL_DOCUMENT_ORGANIZATION_ID VARCHAR(50) NOT NULL, 
LEGAL_DOCUMENT_SECURE_DEK TEXT NOT NULL, 
CONSTRAINT FK_LEGAL_DOCUMENT_TYPE_ID FOREIGN KEY (LEGAL_DOCUMENT_TYPE_ID) REFERENCES capstonelegalschema.LEGAL_DOCUMENT_TYPE(LEGAL_DOCUMENT_TYPE_ID),
CONSTRAINT FK_LEGAL_DOCUMENT_ORGANIZATION_ID FOREIGN KEY (LEGAL_DOCUMENT_ORGANIZATION_ID) REFERENCES capstonelegalschema.ORGANIZATION(ORGANIZATION_ID)
);

CREATE TABLE capstonelegalschema.LEGAL_DOCUMENT_TEMPLATE ( 
LEGAL_DOCUMENT_TEMPLATE_ID VARCHAR(50) PRIMARY KEY, 
LEGAL_DOCUMENT_TEMPLATE_NAME VARCHAR(100) NOT NULL, 
LEGAL_DOCUMENT_TEMPLATE_DOCUMENT BYTEA,
LEGAL_DOCUMENT_TEMPLATE_DESCRIPTION VARCHAR(300) NOT NULL
);

CREATE TABLE capstonelegalschema.LEGAL_MATTER_EMPLOYEES_ASSOCIATION ( 
LEGAL_MATTER_EMPLOYEES_ASSOCIATION_ID VARCHAR(50) PRIMARY KEY,
LEGAL_MATTER_EMPLOYEES_ASSOCIATION_LEGAL_CASE_ID VARCHAR(50) NOT NULL,
LEGAL_MATTER_EMPLOYEES_ASSOCIATION_EMPLOYEE_ID VARCHAR(50) NOT NULL,
CONSTRAINT FK_LEGAL_MATTER_EMPLOYEES_ASSOCIATION_EMPLOYEE_ID FOREIGN KEY (LEGAL_MATTER_EMPLOYEES_ASSOCIATION_EMPLOYEE_ID) REFERENCES capstonelegalschema.EMPLOYEE(EMPLOYEE_ID),
CONSTRAINT FK_LEGAL_MATTER_EMPLOYEES_ASSOCIATION_LEGAL_CASE_ID FOREIGN KEY (LEGAL_MATTER_EMPLOYEES_ASSOCIATION_LEGAL_CASE_ID) REFERENCES capstonelegalschema.LEGAL_CASE(LEGAL_CASE_ID)
);

CREATE TABLE capstonelegalschema.LEGAL_MATTER_DOCUMENTS_ASSOCIATION ( 
LEGAL_MATTER_DOCUMENTS_ASSOCIATION_ID VARCHAR(50) PRIMARY KEY,
LEGAL_MATTER_DOCUMENTS_ASSOCIATION_LEGAL_CASE_ID VARCHAR(50) NOT NULL,
LEGAL_MATTER_DOCUMENTS_ASSOCIATION_LEGAL_DOCUMENT_ID VARCHAR(50) NOT NULL,
CONSTRAINT FK_LEGAL_MATTER_DOCUMENTS_ASSOCIATION_LEGAL_DOCUMENT_ID FOREIGN KEY (LEGAL_MATTER_DOCUMENTS_ASSOCIATION_LEGAL_DOCUMENT_ID) REFERENCES capstonelegalschema.LEGAL_DOCUMENT(LEGAL_DOCUMENT_ID),
CONSTRAINT FK_LEGAL_MATTER_DOCUMENTS_ASSOCIATION_LEGAL_CASE_ID FOREIGN KEY (LEGAL_MATTER_DOCUMENTS_ASSOCIATION_LEGAL_CASE_ID) REFERENCES capstonelegalschema.LEGAL_CASE(LEGAL_CASE_ID)
);

CREATE TABLE capstonelegalschema.LEGAL_MATTER_COURT_ASSOCIATION ( 
LEGAL_MATTER_COURT_ASSOCIATION_ID VARCHAR(50) PRIMARY KEY,
LEGAL_MATTER_COURT_ASSOCIATION_LEGAL_CASE_ID VARCHAR(50) NOT NULL,
LEGAL_MATTER_COURT_ASSOCIATION_COURT_ID VARCHAR(50) NOT NULL,
CONSTRAINT FK_LEGAL_MATTER_COURT_ASSOCIATION_COURT_ID FOREIGN KEY (LEGAL_MATTER_COURT_ASSOCIATION_COURT_ID) REFERENCES capstonelegalschema.COURT(COURT_ID),
CONSTRAINT FK_LEGAL_MATTER_COURT_ASSOCIATION_LEGAL_CASE_ID FOREIGN KEY (LEGAL_MATTER_COURT_ASSOCIATION_LEGAL_CASE_ID) REFERENCES capstonelegalschema.LEGAL_CASE(LEGAL_CASE_ID)
);

CREATE TABLE capstonelegalschema.LEGAL_MATTER_JUDGE_ASSOCIATION ( 
LEGAL_MATTER_JUDGE_ASSOCIATION_ID VARCHAR(50) PRIMARY KEY,
LEGAL_MATTER_JUDGE_ASSOCIATION_LEGAL_CASE_ID VARCHAR(50) NOT NULL,
LEGAL_MATTER_JUDGE_ASSOCIATION_COURT_ID VARCHAR(50) NOT NULL,
CONSTRAINT FK_LEGAL_MATTER_JUDGE_ASSOCIATION_COURT_ID FOREIGN KEY (LEGAL_MATTER_JUDGE_ASSOCIATION_COURT_ID) REFERENCES capstonelegalschema.JUDGE(JUDGE_ID),
CONSTRAINT FK_LEGAL_MATTER_JUDGE_ASSOCIATION_LEGAL_CASE_ID FOREIGN KEY (LEGAL_MATTER_JUDGE_ASSOCIATION_LEGAL_CASE_ID) REFERENCES capstonelegalschema.LEGAL_CASE(LEGAL_CASE_ID)
);

CREATE TABLE capstonelegalschema.LEGAL_MATTER_CONTACT_ASSOCIATION ( 
LEGAL_MATTER_CONTACT_ASSOCIATION_ID VARCHAR(50) PRIMARY KEY,
LEGAL_MATTER_CONTACT_ASSOCIATION_LEGAL_CASE_ID VARCHAR(50) NOT NULL,
LEGAL_MATTER_CONTACT_ASSOCIATION_COURT_ID VARCHAR(50) NOT NULL,
CONSTRAINT FK_LEGAL_MATTER_CONTACT_ASSOCIATION_COURT_ID FOREIGN KEY (LEGAL_MATTER_CONTACT_ASSOCIATION_COURT_ID) REFERENCES capstonelegalschema.CONTACT(CONTACT_ID),
CONSTRAINT FK_LEGAL_MATTER_CONTACT_ASSOCIATION_LEGAL_CASE_ID FOREIGN KEY (LEGAL_MATTER_CONTACT_ASSOCIATION_LEGAL_CASE_ID) REFERENCES capstonelegalschema.LEGAL_CASE(LEGAL_CASE_ID)
);

CREATE TABLE capstonelegalschema.TASK (
TASK_ID VARCHAR(50) PRIMARY KEY,
TASK_DESCRIPTION VARCHAR(200) NOT NULL,
TASK_CREATED_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'IST') NOT NULL,
TASK_LEGAL_CASE_ID VARCHAR(50) NOT NULL,
TASK_CREATED_BY VARCHAR(50) NOT NULL,
TASK_LAST_UPDATED_BY VARCHAR(50),
TASK_LAST_UPDATED_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'IST'),
CONSTRAINT FK_TASK_LEGAL_CASE_ID FOREIGN KEY (TASK_LEGAL_CASE_ID) REFERENCES capstonelegalschema.LEGAL_CASE(LEGAL_CASE_ID),
CONSTRAINT FK_TASK_CREATED_BY FOREIGN KEY (TASK_CREATED_BY) REFERENCES capstonelegalschema.EMPLOYEE(EMPLOYEE_ID),
CONSTRAINT FK_TASK_LAST_UPDATED_BY FOREIGN KEY (TASK_LAST_UPDATED_BY) REFERENCES capstonelegalschema.EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE capstonelegalschema.AUDIT_LOG (
AUDIT_LOG_ID VARCHAR(50) PRIMARY KEY,
AUDIT_LOG_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
AUDIT_LOG_CASE_ID VARCHAR(50) NOT NULL,
AUDIT_LOG_ENTRY TEXT NOT NULL,
CONSTRAINT FK_AUDIT_LOG_CASE_ID FOREIGN KEY (AUDIT_LOG_CASE_ID) REFERENCES capstonelegalschema.LEGAL_CASE(LEGAL_CASE_ID)
);

CREATE INDEX idx_country_name ON capstonelegalschema.COUNTRY (COUNTRY_NAME);

CREATE INDEX idx_state_name ON capstonelegalschema.STATE (STATE_NAME);

CREATE INDEX idx_district_name ON capstonelegalschema.DISTRICT (DISTRICT_NAME);

CREATE INDEX idx_city_name ON capstonelegalschema.CITY (CITY_NAME);

CREATE INDEX idx_contact_type_name ON capstonelegalschema.CONTACT_TYPE (CONTACT_TYPE_NAME);

CREATE INDEX idx_contact_country_id ON capstonelegalschema.CONTACT (CONTACT_COUNTRY_ID);

CREATE INDEX idx_contact_state_id ON capstonelegalschema.CONTACT (CONTACT_STATE_ID);

CREATE INDEX idx_contact_district_id ON capstonelegalschema.CONTACT (CONTACT_DISTRICT_ID);

CREATE INDEX idx_contact_city_id ON capstonelegalschema.CONTACT (CONTACT_CITY_ID);

CREATE INDEX idx_contact_credentials_id ON capstonelegalschema.CONTACT (CONTACT_CREDENTIALS_ID);

CREATE INDEX idx_organization_name ON capstonelegalschema.ORGANIZATION (ORGANIZATION_NAME);

CREATE INDEX idx_department_name ON capstonelegalschema.DEPARTMENT (DEPARTMENT_NAME);

CREATE INDEX idx_role_name ON capstonelegalschema.ROLE (ROLE_NAME);

CREATE INDEX idx_legal_practice_type_name ON capstonelegalschema.LEGAL_PRACTICE_TYPE (LEGAL_PRACTICE_TYPE_NAME);

CREATE INDEX idx_legal_practice_sub_category_name ON capstonelegalschema.LEGAL_PRACTICE_SUB_CATEGORY (LEGAL_PRACTICE_SUB_CATEGORY_NAME);
